Re-generated baseline based on `vimeo/psalm:^5.4`
Note: this introduces a new detected error:

```
ERROR: MixedArgument - src/Role.php:74:58 - Argument 2 of array_merge cannot be mixed, expecting TValue (see https://psalm.dev/030)
                $permissions = array_merge($permissions, $child->getPermissions());
```

That is because in this code, `$child` is a `RoleInterface`
instance, but `RoleInterface#getPermissions()` is not
part of the interface: only the concrete `Role` class
declares it, hence the reason why `mixed` is inferred.